[project]
type = "monorepo"
apps = ["backend", "frontend"]

[[apps]]
name = "backend"
path = "backend"
builder = "java-maven"
start = "java -jar target/*.jar"

[[apps]]
name = "frontend"
path = "frontend"
builder = "node"
build = "npm run build"
start = "npm run dev"
